services:
  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanager
    ports:
      - '5555:3306'
    volumes:
      - './dbdata:/var/lib/mysql/'
    restart: always